version: '3.9'

services:
  db:
    image: postgres:15
    container_name: mini_app_db
    environment:
      POSTGRES_USER: urs123
      POSTGRES_PASSWORD: urs123
      POSTGRES_DB: dev_db
    ports:
      - "5432:5432"
    restart: always